default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: db/development.sqlite3
test:
  <<: *default
  database: db/test.sqlite3
production:
  adapter: postgresql
  url: <%= ENV["POSTGRESQL_URL"] ||  ENV['DATABASE_URL'] || '' %>
  pool: 15
